sudo: false

language: java

jdk:
 - oraclejdk7

language: python

python:
 - "2.7"

notifications:
  email: false

services:
  - redis-server

install:
 - redis-server > /dev/null 2>&1 &
 - virtualenv qabel-drop
 - source qabel-drop/bin/activate
 - pip install -r qabel-drop/requirements.txt

script:
 - travis_wait ./gradlew check
