sudo: false

language: python

python:
 - "2.7"

cache: pip

notifications:
  email: false

services:
  - redis-server

install:
 - virtualenv qabel-drop
 - source qabel-drop/bin/activate
 - pip install -r qabel-drop/requirements.txt

script:
 - travis_wait ./gradlew check
